In [1]:
import pandas as pd
import glob
from matplotlib import pylab as plt
pd.set_option('display.max_rows', 100)

In [2]:
d = {f: pd.read_csv(f) for f in glob.glob('*.csv')}
d.keys()

dict_keys(['cp1500_all_overall_rankings.csv', 'cp1500_all_overall_rankings(1).csv', 'cp10000_all_overall_rankings.csv', 'cp10000_all_overall_rankings(1).csv', 'cp2500_all_overall_rankings.csv', 'cp2500_all_overall_rankings(1).csv'])

In [3]:
def getdf(cp='1500',d=d):
    dd = {}
    for i,row in d[f'cp{cp}_all_overall_rankings.csv'].iterrows():
        dd[row['Pokemon']] = {'old':i+1}
    for i,row in d[f'cp{cp}_all_overall_rankings(1).csv'].iterrows():
        dd[row['Pokemon']]['new']=i+1
    for mon in dd:
        dd[mon]['delta'] = dd[mon]['old'] - dd[mon]['new']
    df = pd.DataFrame.from_dict(dd,orient='index')
    return df
gl = getdf()
ul = getdf('2500')
ml = getdf('10000')

gl[gl['old']<100].sort_values('delta',ascending=False)

                             old  new  delta
Hippowdon (Shadow)            97   46     51
Walrein                       84   37     47
Greninja                      81   35     46
Machamp                       63   21     42
Aurorus                       56   19     37
Machamp (Shadow)              44    8     36
Regirock                      52   26     26
Dewgong                       85   65     20
Toxapex                       33   15     18
Clodsire                      18    1     17
Whiscash                      65   50     15
Sandslash (Alolan)            43   30     13
Feraligatr                    16    3     13
Sandslash (Alolan) (Shadow)   49   38     11
Whimsicott                    76   68      8
Arctibax                      78   72      6
Zweilous                      93   88      5
Mandibuzz                     12    7      5
Whiscash (Shadow)             36   31      5
Gallade (Shadow)              25   20      5
Quagsire                      27   22      5
Steelix (Shadow)              58   53      5
Steelix                       39   36      3
Feraligatr (Shadow)            6    4      2
Lanturn                       67   66      1
Carbink                        2    2      0
Bastiodon                      8    9     -1
Magnezone                     98  101     -3
Meganium                      87   90     -3
Wigglytuff                    59   64     -5
Quagsire (Shadow)              7   12     -5
Hakamo-o                      34   40     -6
Stunfisk                      89   95     -6
Lurantis                      71   77     -6
Venusaur                      92   98     -6
Togedemaru                    72   79     -7
Serperior                     42   49     -7
Azumarill                     11   18     -7
Ninetales (Alolan)            94  102     -8
Kommo-o                       54   62     -8
Gallade                       47   60    -13
Gogoat                        60   73    -13
Guzzlord                      28   43    -15
Bastiodon (Shadow)            15   32    -17
Dragonite (Shadow)            79   99    -20
Goodra                        31   51    -20
Talonflame                    53   75    -22
Registeel                      1   24    -23
Ninetales (Alolan) (Shadow)   61   85    -24
Abomasnow (Shadow)            40   71    -31
Swampert                      13   47    -34
Meganium (Shadow)             91  130    -39
Swampert (Shadow)             14   54    -40
Cresselia (Shadow)            62  105    -43
Cresselia                     23   67    -44
Sableye                       68  112    -44
Pachirisu                     83  127    -44
Dragonair (Shadow)            37   83    -46
Registeel (Shadow)            51   97    -46
Giratina (Origin)             96  147    -51
Lickitung                     10   63    -53
Stunfisk (Galarian)           24   78    -54
Tropius                       82  141    -59
Dragonair                     50  109    -59
Dubwool                       73  134    -61
Venusaur (Shadow)             64  126    -62
Cradily                       99  163    -64
Trevenant                     57  121    -64
Cetoddle                      48  120    -72
Poliwrath                     55  137    -82
Scrafty                       95  180    -85
Skeledirge                    88  175    -87
Empoleon (Shadow)             17  113    -96
Charjabug                     46  146   -100
Gligar (Shadow)                9  122   -113
Empoleon                      20  135   -115
Medicham                      21  143   -122
Altaria                       77  201   -124
Jellicent                     38  165   -127
Cetitan                       66  197   -131
Gligar                        19  153   -134
Skarmory                       4  140   -136
Annihilape                     3  145   -142
Tapu Fini                     75  220   -145
Gliscor                       86  238   -152
Poliwrath (Shadow)            32  191   -159
Pelipper                      22  189   -167
Deoxys (Defense)              69  248   -179
Hitmontop                     70  271   -201
Mantine                        5  212   -207
Skarmory (Shadow)             29  273   -244
Wobbuffet                     90  364   -274
Hitmontop (Shadow)            74  350   -276
Golbat (Shadow)               41  345   -304
Vigoroth                      30  349   -319
Golbat                        80  406   -326
Pidgeot                       35  368   -333
Pidgeot (Shadow)              45  419   -374

In [4]:
ul[ul['new']<100].sort_values('delta',ascending=False)

                             old  new  delta
Dusknoir                     437   14    423
Dusknoir (Shadow)            415   15    400
Golurk                       418   82    336
Golurk (Shadow)              344   52    292
Pangoro                      252    4    248
Drifblim                     209   28    181
Drifblim (Shadow)            198   26    172
Lokix                        256   88    168
Ninetales (Shadow)           200   56    144
Oranguru                     216   73    143
Ursaring (Shadow)            184   49    135
Primeape                     183   59    124
Miltank                      141   34    107
Clodsire                     187   86    101
Gastrodon                    119   24     95
Lickilicky                    98    5     93
Drapion                      112   23     89
Skuntank                     123   36     87
Decidueye                    155   71     84
Machamp                      110   29     81
Weezing (Galarian)            97   19     78
Moltres (Galarian)           108   31     77
Clefable                      78    3     75
Ninetales                    125   57     68
Drapion (Shadow)              81   13     68
Runerigus                     99   47     52
Skuntank (Shadow)             82   30     52
Umbreon                      121   69     52
Florges                       57   12     45
Overqwil                     126   81     45
Machamp (Shadow)              54    9     45
Flygon (Shadow)              111   72     39
Kommo-o                       71   32     39
Incineroar                   115   77     38
Nidoqueen                     91   60     31
Nidoqueen (Shadow)            86   55     31
Turtonator                   130   99     31
Hippowdon                     93   63     30
Regice                       104   75     29
Sneasler (Shadow)             74   45     29
Salazzle                     120   94     26
Aurorus                       46   21     25
Sandslash (Alolan)           113   89     24
Dragonite                    105   83     22
Blastoise                     67   50     17
Tentacruel (Shadow)           79   62     17
Steelix                       36   20     16
Hippowdon (Shadow)            69   53     16
Ninetales (Alolan) (Shadow)   72   58     14
Greninja                      52   38     14
Steelix (Shadow)              29   16     13
Abomasnow                     77   65     12
Regirock (Shadow)             33   22     11
Dragalge                      47   37     10
Sandslash (Alolan) (Shadow)   89   79     10
Regirock                      19   10      9
Walrein (Shadow)              51   43      8
Cobalion                      13    6      7
Tentacruel                    49   42      7
Zygarde (Complete Forme)       7    1      6
Kyurem                        83   78      5
Goodra                        38   33      5
Gyarados                      92   87      5
Walrein                       48   46      2
Gyarados (Shadow)             85   84      1
Feraligatr (Shadow)            2    2      0
Sneasler                      96   96      0
Dragonite (Shadow)            40   40      0
Gengar (Shadow)               65   66     -1
Virizion                      16   18     -2
Mandibuzz                     15   17     -2
Feraligatr                     5    7     -2
Guzzlord                      20   25     -5
Talonflame                    21   27     -6
Registeel                      1    8     -7
Gallade                       90   97     -7
Giratina (Altered)             3   11     -8
Skeledirge                    31   44    -13
Politoed (Shadow)             76   93    -17
Abomasnow (Shadow)            63   80    -17
Cresselia                     14   35    -21
Meganium                      59   85    -26
Trevenant                     42   68    -26
Staraptor (Shadow)            39   67    -28
Cresselia (Shadow)            23   51    -28
Meganium (Shadow)             41   70    -29
Serperior                     66   95    -29
Venusaur                      60   90    -30
Swampert                      17   48    -31
Gallade (Shadow)              32   64    -32
Giratina (Origin)             58   91    -33
Venusaur (Shadow)             43   76    -33
Cofagrigus                    64   98    -34
Poliwrath                      6   41    -35
Tapu Fini                      4   39    -35
Swampert (Shadow)             18   54    -36
Registeel (Shadow)             9   61    -52
Zapdos (Shadow)               34   92    -58
Poliwrath (Shadow)            10   74    -64

In [7]:
ml[ml['new']<100].sort_values('new',ascending=True)

                          old  new  delta
Zygarde (Complete Forme)    2    1      1
Palkia (Origin)             1    2     -1
Yveltal                    44    3     41
Solgaleo                   11    4      7
Necrozma (Dusk Mane)       15    5     10
Rhyperior                  82    6     76
Ho-Oh                      16    7      9
Ho-Oh (Shadow)             27    8     19
Florges                    34    9     25
Kyurem                     13   10      3
Landorus (Therian)          3   11     -8
Necrozma (Dawn Wings)       7   12     -5
Palkia                      6   13     -7
Giratina (Altered)          5   14     -9
Marshadow                  32   15     17
Moltres (Galarian)        149   16    133
Xerneas                    18   17      1
Dragonite                   4   18    -14
Rhyperior (Shadow)         92   19     73
Dragonite (Shadow)          9   20    -11
Meloetta (Aria)            12   21     -9
Ursaluna                   43   22     21
Mewtwo (Shadow)            14   23     -9
Reshiram                   23   24     -1
Giratina (Origin)          10   25    -15
Gyarados (Shadow)          24   26     -2
Enamorus (Incarnate)       78   27     51
Tapu Lele                  94   28     66
Dialga (Origin)            21   29     -8
Zekrom                     19   30    -11
Groudon                     8   31    -23
Mewtwo                     17   32    -15
Ursaluna (Shadow)          39   33      6
Avalugg (Hisuian)          25   34     -9
Hydreigon                  46   35     11
Zacian (Hero)              33   36     -3
Zarude                     29   37     -8
Gyarados                   30   38     -8
Groudon (Shadow)           20   39    -19
Baxcalibur                 38   40     -2
Dialga                     36   41     -5
Goodra                     28   42    -14
Heatran                    68   43     25
Mamoswine                  40   44     -4
Feraligatr                 75   45     30
Gholdengo                  90   46     44
Mamoswine (Shadow)         48   47      1
Hippowdon (Shadow)         73   48     25
Garchomp                   41   49     -8
Latios (Shadow)            37   50    -13
Feraligatr (Shadow)        63   51     12
Genesect (Chill)           64   52     12
Metagross                  55   53      2
Lugia                      22   54    -32
Tapu Bulu                  59   55      4
Kyogre                     26   56    -30
Togekiss                  101   57     44
Sneasler (Shadow)          96   58     38
Zapdos (Shadow)            67   59      8
Cetitan                    35   60    -25
Kommo-o                    54   61     -7
Necrozma                   69   62      7
Swampert                   45   63    -18
Tyranitar (Shadow)         97   64     33
Snorlax (Shadow)           65   65      0
Hoopa (Unbound)           199   66    133
Golisopod                  72   67      5
Zygarde (50% Forme)        58   68    -10
Hippowdon                  85   69     16
Keldeo (Ordinary)          66   70     -4
Kyogre (Shadow)            31   71    -40
Primarina                 122   72     50
Zamazenta (Hero)           62   73    -11
Regirock (Shadow)          76   74      2
Nihilego                   87   75     12
Pangoro                   167   76     91
Rayquaza                   61   77    -16
Skeledirge                115   78     37
Swampert (Shadow)          47   79    -32
Zapdos                     79   80     -1
Garchomp (Shadow)          77   81     -4
Landorus (Incarnate)       49   82    -33
Tyranitar                 102   83     19
Raikou (Shadow)            91   84      7
Excadrill (Shadow)         88   85      3
Tapu Fini                  60   86    -26
Latios                     51   87    -36
Regirock                   83   88     -5
Salamence                  70   89    -19
Entei                     129   90     39
Raikou                     99   91      8
Cobalion                   89   92     -3
Lugia (Shadow)             42   93    -51
Mew                        86   94     -8
Terrakion                  74   95    -21
Virizion                   52   96    -44
Metagross (Shadow)        100   97      3
Salamence (Shadow)         84   98    -14
Entei (Shadow)            146   99     47